"""Provider abstraction. Wraps litellm + a dry-run canned-response provider."""
from __future__ import annotations

import asyncio
import random
import time
from dataclasses import dataclass
from typing import Any

from .config import BenchConfig, ModelConfig


SYSTEM_PROMPT = (
    "You are an expert front-end engineer. "
    "Respond with exactly ONE self-contained HTML5 document. "
    "Do NOT wrap it in markdown code fences. "
    "Do NOT include any commentary, preamble, or trailing text. "
    "The response must start with <!DOCTYPE html> and end with </html>."
)


@dataclass
class CompletionResult:
    text: str
    latency_ms: int
    prompt_tokens: int | None
    completion_tokens: int | None
    total_tokens: int | None
    cost_usd: float | None
    error: str | None = None


# A canned, deliberately mixed-quality HTML pool so the dashboard's
# overview / compare / error detector views all have varied data in dry-run.
_DRY_RUN_TEMPLATES: list[str] = [
    # 0 - clean, valid
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Dry-run sample {PROMPT}</title>
<style>
body{{font-family:system-ui,sans-serif;background:#0b0c10;color:#e8e8e8;margin:0;padding:2rem}}
h1{{color:#7ee787}}
</style>
</head>
<body>
<h1>Dry-run output for: {PROMPT}</h1>
<p>This is a synthetic, valid HTML response generated by the dry-run provider as model <code>{MODEL}</code>.</p>
<p>It contains no JavaScript errors and parses cleanly.</p>
</body>
</html>""",
    # 1 - missing doctype, missing </body>
    """<html>
<head><title>Dry-run sample {PROMPT}</title></head>
<body>
<h1>{PROMPT} - {MODEL}</h1>
<p>This sample is missing the doctype and an end tag, to exercise the validator.</p>
</html>""",
    # 2 - throws a JS console error
    """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Dry-run JS error</title>
</head>
<body>
<h1>{PROMPT} - {MODEL}</h1>
<p>This page intentionally throws a runtime error.</p>
<script>
  // Reference to an undefined variable to trigger a console error.
  console.log(somethingThatDoesNotExist);
</script>
</body>
</html>""",
    # 3 - duplicate IDs
    """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Dup IDs</title></head>
<body>
<div id="main">A</div>
<div id="main">B</div>
<p>{PROMPT} via {MODEL}</p>
</body>
</html>""",
]


def _render_dry_run(model_id: str, prompt_id: str, prompt_body: str) -> str:
    # Stable, deterministic-ish pick per (prompt, model) so reruns are stable
    # but different models look different.
    rng = random.Random(f"{prompt_id}|{model_id}")
    template = rng.choice(_DRY_RUN_TEMPLATES)
    return template.format(PROMPT=prompt_id, MODEL=model_id)


async def _complete_dry_run(model: ModelConfig, prompt_id: str, prompt_body: str) -> CompletionResult:
    started = time.perf_counter()
    # Simulate latency so the UI/preflight feels realistic.
    await asyncio.sleep(0.1 + random.random() * 0.2)
    text = _render_dry_run(model.id, prompt_id, prompt_body)
    elapsed = int((time.perf_counter() - started) * 1000)
    return CompletionResult(
        text=text,
        latency_ms=elapsed,
        prompt_tokens=len(prompt_body) // 4,
        completion_tokens=len(text) // 4,
        total_tokens=(len(prompt_body) + len(text)) // 4,
        cost_usd=0.0,
    )


_litellm_rebuilt = False


def _ensure_litellm_models_rebuilt() -> None:
    """Work around a litellm 1.97.0 packaging bug.

    `litellm.types.utils` imports `ChatCompletionReasoningItem` but not the
    `ChatCompletionReasoningSummaryTextBlock` it forward-references, so under
    pydantic 2.11+ the `Message` model can never be fully defined and even
    constructing a `ModelResponse` raises PydanticUserError. We inject the
    missing name into that module namespace and rebuild the model once.

    No-op (and silently ignored) once a fixed litellm ships the import itself.
    """
    global _litellm_rebuilt
    if _litellm_rebuilt:
        return
    try:
        import litellm.types.utils as _u
        from litellm.types.llms.openai import ChatCompletionReasoningSummaryTextBlock

        if not hasattr(_u, "ChatCompletionReasoningSummaryTextBlock"):
            setattr(_u, "ChatCompletionReasoningSummaryTextBlock", ChatCompletionReasoningSummaryTextBlock)
            _u.Message.model_rebuild(force=True)
    except Exception:  # noqa: BLE001 - best-effort shim; real errors surface at call time
        pass
    _litellm_rebuilt = True


async def _complete_litellm(
    model: ModelConfig, defaults: Any, prompt_id: str, prompt_body: str
) -> CompletionResult:
    # Import locally so dry-run mode does not require litellm at import time
    # for environments that just want to test the bench harness.
    import litellm

    _ensure_litellm_models_rebuilt()

    # For a local OpenAI-compatible server (llama.cpp, LM Studio, vLLM, ...) the
    # server knows the model by the name it reports on /v1/models. We pass that
    # via `model_name` and tell litellm via the openai/<name> wire format.
    if model.is_openai_compatible_local and model.model_name:
        wire_model = f"openai/{model.model_name}"
    else:
        wire_model = model.provider

    kwargs: dict[str, Any] = {
        "model": wire_model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt_body},
        ],
        "temperature": model.temperature if model.temperature is not None else defaults.temperature,
        "max_tokens": model.max_tokens if model.max_tokens is not None else defaults.max_tokens,
        "timeout": model.timeout_s if model.timeout_s is not None else defaults.timeout_s,
    }
    if model.api_base:
        kwargs["api_base"] = model.api_base
    if model.api_key:
        kwargs["api_key"] = model.api_key

    started = time.perf_counter()
    try:
        response = await litellm.acompletion(**kwargs)
    except Exception as exc:  # noqa: BLE001 - we surface the message to the user
        elapsed = int((time.perf_counter() - started) * 1000)
        return CompletionResult(
            text="",
            latency_ms=elapsed,
            prompt_tokens=None,
            completion_tokens=None,
            total_tokens=None,
            cost_usd=None,
            error=f"{type(exc).__name__}: {exc}",
        )
    elapsed = int((time.perf_counter() - started) * 1000)

    text = ""
    try:
        text = response.choices[0].message.content or ""
    except Exception:  # pragma: no cover - defensive
        text = ""

    usage = getattr(response, "usage", None)
    prompt_tokens = getattr(usage, "prompt_tokens", None) if usage else None
    completion_tokens = getattr(usage, "completion_tokens", None) if usage else None
    total_tokens = getattr(usage, "total_tokens", None) if usage else None

    cost_usd: float | None
    try:
        cost_usd = float(litellm.completion_cost(completion_response=response) or 0.0)
    except Exception:
        cost_usd = None

    return CompletionResult(
        text=text,
        latency_ms=elapsed,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=total_tokens,
        cost_usd=cost_usd,
    )


async def complete(
    model: ModelConfig, config: BenchConfig, prompt_id: str, prompt_body: str
) -> CompletionResult:
    if model.is_dry_run:
        return await _complete_dry_run(model, prompt_id, prompt_body)
    return await _complete_litellm(model, config.defaults, prompt_id, prompt_body)
